services:
  postgres:
    image: postgres:latest
    container_name: postgres-academy
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpro-test-assignment-password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: